### ISSUE TITLE
vento and VScode doesn't auto complete on tab

### ISSUE THREAD

**Issue by tjaynl** [ventojs/vscode-vento#1]
I'm intressed in using vento but i have the following issue when using it in VSCode, i installed the plugin but vscode still doesn't auto complete on hitting TAB. Same goes for auto completing emmet.

Am i missing something?

**Comment by oscarotero** [comment]
In my VSCode I can press TAB after typing any Vento tag, for example `for`:
<img width="1196" alt="imaxe" src="https://github.com/oscarotero/vscode-vento/assets/377873/d5b01c4b-a4be-4fd5-a4f3-ee4a0b0afbdd">

What keywords are you using?

About emmet support, yes you're right. I have to investigate how to enable emmet by default in the plugin configurarion. As a workaround, you can enable it in the .vscode/settings.json file:

```json
{
  "emmet.includeLanguages": {
    "vento": "html"
  }
}
```

**Comment by oscarotero** [comment]
Ok, I just released v0.0.4 with default support for emmet.

**Comment by tjaynl** [comment]
Thank you for the replies indeed with the update it seems to work, i'll keep you up to date if there are other issues i come a cross, again thanks for the reply.
