### ISSUE TITLE
`from` keyword in import tags not recognized

### ISSUE THREAD

**Issue by uncenter** [ventojs/vscode-vento#11]
```
{{ import x from "y" }}
{{ import { x } from "y" }}
```

![CleanShot 2024-11-17 at 23 30 29](https://github.com/user-attachments/assets/ecf9ac2d-c273-4243-afd8-938908704a8a)

The `from` keyword doesn't appear to be highlighted/recognized by Vento here. If I understand the grammar correctly:
https://github.com/ventojs/vscode-vento/blob/5002687adada021d3399771c3ac8cc2b9414d7cf/syntaxes/vento.tmLanguage.json#L43-L56
This is because the template keyword `import` is matched first, leaving `x from "y"` or `{ x } from "y"` as the part that is set to use JavaScript highlighting. I fixed this locally by just removing `import` from: https://github.com/ventojs/vscode-vento/blob/5002687adada021d3399771c3ac8cc2b9414d7cf/syntaxes/vento.tmLanguage.json#L58

But then the `import` keyword isn't technically set to `keyword.vento`, I'm not sure how important that is (in general / to you).

**Comment by oscarotero** [comment]
Before removing the `import` keyword, can you try adding `from` to the list?
If this doesn't work, but removing `import` does, I'm okay with this change. If you want to work on a PR, I'm happy to merge it :)

**Comment by uncenter** [comment]
> Before removing the `import` keyword, can you try adding `from` to the list?

You are totally right,  that does work 😅.
